[classifier]
optimizer = 'SGD'
batch_size = 256
learning_rate = 0.01
momentum = 0.9
weight_decay = 1e-3
epoch = 100
early_stopping = true
patience = 7
augmentation_level = 'normal'
saving_option = 'top5'

[dataset]
seed = 42

hugging_face = ['flwrlabs/celeba']
hugging_identity = [1000]

kaggle_hub = ['rajnishe/facescrub-full']
kaggle_identity = [200]

### We can add other dataset later, but for now, we don't.
dist_shift_hugging = []
dist_shift_hugging_identity = []

dist_shift_kaggle = []
dist_shift_kaggle_identity = []
