[classifier]
optimizer = 'SGD'
batch_size = 64
learning_rate = 0.01
momentum = 0.9
weight_decay = 1e-4
epoch = 50
early_stopping = true
patience = 7
augmentation_level = 'normal'
saving_option = 'top5'

[dataset]
seed = 42

hugging_face = ['flwrlabs/celeba']
hugging_identity = [1000]

kaggle_hub = ['rajnishe/facescrub-full', 'annasvoboda/pubfig83']
kaggle_identity = [200, 50]

### We can add other dataset later, but for now, we don't.
dist_shift_hugging = []
dist_shift_hugging_identity = []

dist_shift_kaggle = ['arnaud58/flickrfaceshq-dataset-ffhq']
dist_shift_kaggle_identity = [30000]
